version: '3'
services:
  talon:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./talon-data:/home/node/.talon
    environment:
      - TALON_GATEWAY_PORT=3000
      - TALON_HOST=0.0.0.0
